#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# setup git/config.local
"${BASEDIR}/scripts/gitconfig.local.sh"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

source ~/.zshenv
# macos defaluts: https://macos-defaults.com
# ref: https://github.com/mathiasbynens/dotfiles/blob/master/.macos
"${BASEDIR}/scripts/macos.sh"
# install homebrew and brew bundle
"${BASEDIR}/scripts/brew.sh"
# install tmux tpm
"${BASEDIR}/scripts/tpm.sh"
# install asdf plugin
"${BASEDIR}/scripts/asdf.sh"
