#!/usr/bin/ruby

require 'irb/completion'
require 'pry'

IRB.conf[:PROMPT_MODE] = :DEFAULT
IRB.conf[:AUTO_INDENT] = true
IRB.conf[:SAVE_HISTORY] = 2000
IRB.conf[:HISTORY_FILE] = "#{ENV['XDG_STATE_HOME']}/ruby/irb_history"
