#!/usr/bin/env zsh

# XDG Paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.local/cache"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# Homebrew paths (only cache if brew is available)
if (( ${+commands[brew]} )); then
  export HOMEBREW_PREFIX="$(brew --prefix)"
else
  export HOMEBREW_PREFIX="/opt/homebrew"
fi
