# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# General Settings
source ${ZDOTDIR}/aliases.zsh
source ${ZDOTDIR}/general.zsh

# Plugin Settings
# zsh-fast-syntax-highlighting
# source $(brew --prefix)/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

export TIMEWARRIORDB=${XDG_DATA_HOME}/timewarrior
export TEALDEER_CONFIG_DIR=${XDG_CONFIG_HOME}/tealdeer
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
export IRBRC="$XDG_CONFIG_HOME/ruby/irbrc"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export PYTHONHISTFILE="$XDG_STATE_HOME/python/history"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export MPLCONFIGDIR="$XDG_CONFIG_HOME/matplotlib"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME/jupyter"

# autocompletion info:
# https://github.com/dbrgn/tealdeer/blob/main/docs/src/installing.md#autocompletion
# asdf install postgres needs pkg-config and icu4c
export LDFLAGS="-L$(brew --prefix icu4c)/lib"
export CPPFLAGS="-I$(brew --prefix icu4c)/include"
export PKG_CONFIG_PATH="$(brew --prefix icu4c)/lib/pkgconfig"

source ${XDG_CONFIG_HOME}/asdf/asdfrc
source "${XDG_DATA_HOME}/asdf/installs/rust/1.83.0/env"

# PATH and FPATH
# PATH=~/.dotfiles/functions:$PATH
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

# Completion
source ${ZDOTDIR}/completion.zsh

source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# zsh-vi-mode 回調函數：在 vi-mode 初始化後重新設定歷史搜尋
function zvm_after_init() {
  bindkey "^[[A" history-beginning-search-backward
  bindkey "^[[B" history-beginning-search-forward
}
source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source $(brew --prefix asdf)/libexec/asdf.sh
source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ${ZDOTDIR}/.p10k.zsh ]] || source ${ZDOTDIR}/.p10k.zsh
