# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# General Settings
source ${ZDOTDIR}/general.zshrc

# Plugin Settings
# zsh-fast-syntax-highlighting
# source $(brew --prefix)/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# timewarrior
export TIMEWARRIORDB=${XDG_DATA_HOME}/timewarrior

# tealdeer aka tldr in rust
export TEALDEER_CONFIG_DIR=${XDG_CONFIG_HOME}/tealdeer
# autocompletion info:
# https://github.com/dbrgn/tealdeer/blob/main/docs/src/installing.md#autocompletion

# PATH and FPATH
FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

# Completion
source ${ZDOTDIR}/completion.zshrc

source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ${ZDOTDIR}/.p10k.zsh ]] || source ${ZDOTDIR}/.p10k.zsh
