#TERM
export TERMINFO="$XDG_DATA_HOME"/zsh/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/zsh/terminfo:/usr/share/terminfo

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# General Settings
# export TERM='xterm-ghostty'
source ${ZDOTDIR}/aliases.zsh
source ${ZDOTDIR}/general.zsh

# Plugin Settings
# zsh-fast-syntax-highlighting
# source $(brew --prefix)/share/zsh-fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

export TIMEWARRIORDB=${XDG_DATA_HOME}/timewarrior
export TEALDEER_CONFIG_DIR=${XDG_CONFIG_HOME}/tealdeer
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export IRBRC="$XDG_CONFIG_HOME/ruby/irbrc"
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export PYTHONHISTFILE="$XDG_STATE_HOME/python/history"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"

# Compiler
# asdf install postgres needs pkg-config and icu4c
export LDFLAGS="-L${HOMEBREW_PREFIX}/opt/icu4c/lib"
export CPPFLAGS="-I${HOMEBREW_PREFIX}/opt/icu4c/include"
export PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/opt/icu4c/lib/pkgconfig"
# curl
export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
export CPPFLAGS="-I/opt/homebrew/opt/curl/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/curl/lib/pkgconfig"

source ${XDG_CONFIG_HOME}/asdf/asdfrc

# PATH and FPATH
# Load custom functions
if [[ -d "$ZDOTDIR/functions" ]]; then
  fpath=($ZDOTDIR/functions $fpath)
  autoload -Uz $ZDOTDIR/functions/*(:t)
fi

# use brewed curl first
PATH=${HOMEBREW_PREFIX}/opt/curl/bin:$PATH
PATH=${HOME}/.local/bin:${XDG_DATA_HOME}/asdf/shims:$PATH
FPATH=${HOMEBREW_PREFIX}/share/zsh-completions:$FPATH

# Completion
source ${ZDOTDIR}/completion.zsh
# tealdeer: https://github.com/dbrgn/tealdeer/blob/main/docs/src/installing.md#autocompletion

source ${HOMEBREW_PREFIX}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ${HOMEBREW_PREFIX}/share/zsh-autosuggestions/zsh-autosuggestions.zsh
# fzf shell integration: https://github.com/junegunn/fzf#setting-up-shell-integration
source <(fzf --zsh)
# zsh-autocomplete must load before zsh-vi-mode
# source ${HOMEBREW_PREFIX}/opt/zsh-autocomplete/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# zsh-vi-mode after vi-mode initialized re-bindkey
function zvm_after_init() {
  # history search bindkey
  bindkey "^[[A" history-beginning-search-backward
  bindkey "^[[B" history-beginning-search-forward

  # Completion menu navigation
  bindkey -M menuselect 'h' vi-backward-char
  bindkey -M menuselect 'k' vi-up-line-or-history
  bindkey -M menuselect 'j' vi-down-line-or-history
  bindkey -M menuselect 'l' vi-forward-char
}
source ${HOMEBREW_PREFIX}/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source ${HOMEBREW_PREFIX}/opt/asdf/libexec/asdf.sh
source ${HOMEBREW_PREFIX}/share/powerlevel10k/powerlevel10k.zsh-theme

# zoxide
export _ZO_DATA_DIR=$XDG_DATA_HOME/zsh
eval "$(zoxide init zsh)"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ${ZDOTDIR}/.p10k.zsh ]] || source ${ZDOTDIR}/.p10k.zsh
